# Category mapping for all 185 skills
$categories = @{
    # === BIOINFORMATICS & COMPUTATIONAL BIOLOGY ===
    "adaptyv" = "bioinformatics"
    "alphafold-database" = "bioinformatics"
    "anndata" = "bioinformatics"
    "arboreto" = "bioinformatics"
    "benchling-integration" = "bioinformatics"
    "bgpt-paper-search" = "bioinformatics"
    "biopython" = "bioinformatics"
    "biorxiv-database" = "bioinformatics"
    "bioservices" = "bioinformatics"
    "brenda-database" = "bioinformatics"
    "cbioportal-database" = "bioinformatics"
    "cellxgene-census" = "bioinformatics"
    "clinpgx-database" = "bioinformatics"
    "clinvar-database" = "bioinformatics"
    "cobrapy" = "bioinformatics"
    "cosmic-database" = "bioinformatics"
    "deeptools" = "bioinformatics"
    "depmap" = "bioinformatics"
    "dnanexus-integration" = "bioinformatics"
    "ena-database" = "bioinformatics"
    "ensembl-database" = "bioinformatics"
    "esm" = "bioinformatics"
    "etetoolkit" = "bioinformatics"
    "flowio" = "bioinformatics"
    "gene-database" = "bioinformatics"
    "geniml" = "bioinformatics"
    "geo-database" = "bioinformatics"
    "gget" = "bioinformatics"
    "glycoengineering" = "bioinformatics"
    "gnomad-database" = "bioinformatics"
    "gtars" = "bioinformatics"
    "gtex-database" = "bioinformatics"
    "gwas-database" = "bioinformatics"
    "histolab" = "bioinformatics"
    "hmdb-database" = "bioinformatics"
    "imaging-data-commons" = "bioinformatics"
    "interpro-database" = "bioinformatics"
    "jaspar-database" = "bioinformatics"
    "kegg-database" = "bioinformatics"
    "labarchive-integration" = "bioinformatics"
    "lamindb" = "bioinformatics"
    "latchbio-integration" = "bioinformatics"
    "metabolomics-workbench-database" = "bioinformatics"
    "monarch-database" = "bioinformatics"
    "neurokit2" = "bioinformatics"
    "neuropixels-analysis" = "bioinformatics"
    "omero-integration" = "bioinformatics"
    "opentargets-database" = "bioinformatics"
    "opentrons-integration" = "bioinformatics"
    "pathml" = "bioinformatics"
    "pdb-database" = "bioinformatics"
    "phylogenetics" = "bioinformatics"
    "protocolsio-integration" = "bioinformatics"
    "pydeseq2" = "bioinformatics"
    "pydicom" = "bioinformatics"
    "pyhealth" = "bioinformatics"
    "pylabrobot" = "bioinformatics"
    "pyopenms" = "bioinformatics"
    "pysam" = "bioinformatics"
    "reactome-database" = "bioinformatics"
    "scanpy" = "bioinformatics"
    "scikit-bio" = "bioinformatics"
    "scikit-survival" = "bioinformatics"
    "scvelo" = "bioinformatics"
    "scvi-tools" = "bioinformatics"
    "string-database" = "bioinformatics"
    "tiledbvcf" = "bioinformatics"
    "uniprot-database" = "bioinformatics"

    # === CHEMINFORMATICS & DRUG DISCOVERY ===
    "bindingdb-database" = "cheminformatics-drug-discovery"
    "chembl-database" = "cheminformatics-drug-discovery"
    "datamol" = "cheminformatics-drug-discovery"
    "deepchem" = "cheminformatics-drug-discovery"
    "diffdock" = "cheminformatics-drug-discovery"
    "drugbank-database" = "cheminformatics-drug-discovery"
    "matchms" = "cheminformatics-drug-discovery"
    "medchem" = "cheminformatics-drug-discovery"
    "molfeat" = "cheminformatics-drug-discovery"
    "pubchem-database" = "cheminformatics-drug-discovery"
    "pytdc" = "cheminformatics-drug-discovery"
    "rdkit" = "cheminformatics-drug-discovery"
    "torchdrug" = "cheminformatics-drug-discovery"
    "zinc-database" = "cheminformatics-drug-discovery"

    # === DATA SCIENCE & MACHINE LEARNING ===
    "aeon" = "data-science-ml"
    "dask" = "data-science-ml"
    "exploratory-data-analysis" = "data-science-ml"
    "hypogenic" = "data-science-ml"
    "matplotlib" = "data-science-ml"
    "networkx" = "data-science-ml"
    "plotly" = "data-science-ml"
    "polars" = "data-science-ml"
    "pufferlib" = "data-science-ml"
    "pymc" = "data-science-ml"
    "pymoo" = "data-science-ml"
    "pytorch-lightning" = "data-science-ml"
    "scikit-learn" = "data-science-ml"
    "seaborn" = "data-science-ml"
    "shap" = "data-science-ml"
    "simpy" = "data-science-ml"
    "stable-baselines3" = "data-science-ml"
    "statistical-analysis" = "data-science-ml"
    "statsmodels" = "data-science-ml"
    "sympy" = "data-science-ml"
    "timesfm-forecasting" = "data-science-ml"
    "torch-geometric" = "data-science-ml"
    "transformers" = "data-science-ml"
    "umap-learn" = "data-science-ml"
    "vaex" = "data-science-ml"
    "zarr-python" = "data-science-ml"

    # === SCIENTIFIC WRITING & RESEARCH ===
    "citation-management" = "scientific-writing-research"
    "consciousness-council" = "scientific-writing-research"
    "hypothesis-generation" = "scientific-writing-research"
    "latex-posters" = "scientific-writing-research"
    "literature-review" = "scientific-writing-research"
    "markdown-mermaid-writing" = "scientific-writing-research"
    "market-research-reports" = "scientific-writing-research"
    "medical-imaging-review" = "scientific-writing-research"
    "nsfc-proposal" = "scientific-writing-research"
    "nssfc-proposal" = "scientific-writing-research"
    "paper-2-web" = "scientific-writing-research"
    "paper-slide-deck" = "scientific-writing-research"
    "peer-review" = "scientific-writing-research"
    "research-grants" = "scientific-writing-research"
    "research-lookup" = "scientific-writing-research"
    "research-proposal" = "scientific-writing-research"
    "scholar-evaluation" = "scientific-writing-research"
    "scientific-brainstorming" = "scientific-writing-research"
    "scientific-critical-thinking" = "scientific-writing-research"
    "scientific-schematics" = "scientific-writing-research"
    "scientific-slides" = "scientific-writing-research"
    "scientific-visualization" = "scientific-writing-research"
    "scientific-writing" = "scientific-writing-research"
    "venue-templates" = "scientific-writing-research"
    "what-if-oracle" = "scientific-writing-research"

    # === DATABASES & APIs ===
    "alpha-vantage" = "databases-apis"
    "datacommons-client" = "databases-apis"
    "edgartools" = "databases-apis"
    "fred-economic-data" = "databases-apis"
    "get-available-resources" = "databases-apis"
    "hedgefundmonitor" = "databases-apis"
    "openalex-database" = "databases-apis"
    "perplexity-search" = "databases-apis"
    "pubmed-database" = "databases-apis"
    "usfiscaldata" = "databases-apis"
    "uspto-database" = "databases-apis"
    "parallel-web" = "databases-apis"

    # === QUANTUM COMPUTING ===
    "cirq" = "quantum-computing"
    "pennylane" = "quantum-computing"
    "qiskit" = "quantum-computing"
    "qutip" = "quantum-computing"

    # === GEOSPATIAL ===
    "geomaster" = "geospatial"
    "geopandas" = "geospatial"

    # === PHYSICS & ENGINEERING ===
    "astropy" = "physics-engineering"
    "fluidsim" = "physics-engineering"
    "pymatgen" = "physics-engineering"
    "rowan" = "physics-engineering"

    # === DOCUMENTS & PRESENTATIONS ===
    "docx" = "documents-presentations"
    "infographics" = "documents-presentations"
    "markitdown" = "documents-presentations"
    "pdf" = "documents-presentations"
    "pptx" = "documents-presentations"
    "pptx-posters" = "documents-presentations"
    "xlsx" = "documents-presentations"

    # === CLINICAL & MEDICAL ===
    "clinical-decision-support" = "clinical-medical"
    "clinical-reports" = "clinical-medical"
    "clinicaltrials-database" = "clinical-medical"
    "fda-database" = "clinical-medical"
    "iso-13485-certification" = "clinical-medical"
    "treatment-plans" = "clinical-medical"

    # === CHINESE ACADEMIC ===
    "qinyan-citation" = "chinese-academic"
    "qinyan-paper-analysis" = "chinese-academic"
    "qinyan-paper-polish" = "chinese-academic"
    "qinyan-paper-search" = "chinese-academic"
    "qinyan-topic-analysis" = "chinese-academic"

    # === AI & AUTOMATION TOOLS ===
    "claude-skill-registry" = "ai-automation"
    "denario" = "ai-automation"
    "dhdna-profiler" = "ai-automation"
    "generate-image" = "ai-automation"
    "ginkgo-cloud-lab" = "ai-automation"
    "modal" = "ai-automation"
    "offer-k-dense-web" = "ai-automation"
    "open-notebook" = "ai-automation"

    # === FINANCE & ECONOMICS ===
    # (alpha-vantage, fred, etc already in databases-apis; 
    #  this is for dedicated finance skills if any)
}
